AWSTemplateFormatVersion: '2010-09-09'
Description: >
  WebForx AppStream VDI: Fleet + Stack + optional ImageBuilder, Home Folders, step scaling, and schedules.

Parameters:
  VPCId:
    Type: String
  SubnetId:
    Type: String
  SecurityGroupId:
    Type: String
  FleetName:
    Type: String
    Default: webforx-vdi-fleet
  FleetInstanceType:
    Type: String
    Default: stream.standard.medium
  FleetImageArn:
    Type: String
    Default: ""
    Description: "Image ARN for the Fleet. If blank, BaseImageArn will be used."
  BuilderInstanceType:
    Type: String
    Default: stream.standard.large
  BaseImageArn:
    Type: String
    Default: ""
    Description: "Optional base image ARN for ImageBuilder (leave blank to skip ImageBuilder)."
  MinCapacity:
    Type: Number
    Default: 0
  DesiredCapacity:
    Type: Number
    Default: 0
  MaxCapacity:
    Type: Number
    Default: 5
  MaxUserSessionDurationSecs:
    Type: Number
    Default: 14400
  EnableAutoScaling:
    Type: String
    AllowedValues: ["true","false"]
    Default: "true"
  BusinessHoursCronStartUTC:
    Type: String
    Default: "cron(0 13 * * ? *)"
  AfterHoursCronStopUTC:
    Type: String
    Default: "cron(0 22 * * ? *)"

Conditions:
  CreateImageBuilder: !Not [!Equals [!Ref BaseImageArn, ""]]
  EnableScaling: !Equals [!Ref EnableAutoScaling, "true"]
  UseFleetImage: !Not [!Equals [!Ref FleetImageArn, ""]]

Resources:
  AppStreamFleet:
    Type: AWS::AppStream::Fleet
    Properties:
      Name: !Ref FleetName
      InstanceType: !Ref FleetInstanceType
      ImageArn: !If [UseFleetImage, !Ref FleetImageArn, !Ref BaseImageArn]
      ComputeCapacity:
        DesiredInstances: !Ref DesiredCapacity
      VpcConfig:
        SecurityGroupIds: [ !Ref SecurityGroupId ]
        SubnetIds: [ !Ref SubnetId ]   # single subnet
      StreamView: DESKTOP              # <-- desktop sessions
      MaxUserDurationInSeconds: !Ref MaxUserSessionDurationSecs
      DisconnectTimeoutInSeconds: 900
      IdleDisconnectTimeoutInSeconds: 900
      EnableDefaultInternetAccess: false
      FleetType: ON_DEMAND

  AppStreamStack:
    Type: AWS::AppStream::Stack
    Properties:
      Name: !Sub "${FleetName}-stack"
      Description: "AppStream VDI stack"
      StorageConnectors:
        - ConnectorType: HOMEFOLDERS
      UserSettings:
        - Action: CLIPBOARD_COPY_FROM_LOCAL_DEVICE
          Permission: ENABLED
        - Action: CLIPBOARD_COPY_TO_LOCAL_DEVICE
          Permission: ENABLED
        - Action: FILE_UPLOAD
          Permission: ENABLED
        - Action: FILE_DOWNLOAD
          Permission: ENABLED
        - Action: PRINTING_TO_LOCAL_DEVICE
          Permission: ENABLED

  StackFleetAssociation:
    Type: AWS::AppStream::StackFleetAssociation
    Properties:
      FleetName: !Ref AppStreamFleet
      StackName: !Ref AppStreamStack

  ImageBuilder:
    Condition: CreateImageBuilder
    Type: AWS::AppStream::ImageBuilder
    Properties:
      Name: !Sub "${FleetName}-builder"
      DisplayName: !Sub "${FleetName}-builder"
      Description: "Image Builder for AppStream. Use Image Assistant to install dev tools."
      InstanceType: !Ref BuilderInstanceType
      ImageArn: !Ref BaseImageArn
      VpcConfig:
        SecurityGroupIds: [ !Ref SecurityGroupId ]
        SubnetIds: [ !Ref SubnetId ]
      EnableDefaultInternetAccess: false

  ScalableTarget:
    Condition: EnableScaling
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: AppStreamFleet
    Properties:
      MaxCapacity: !Ref MaxCapacity
      MinCapacity: !Ref MinCapacity
      ResourceId: !Sub "fleet/${FleetName}"
      ScalableDimension: appstream:fleet:DesiredCapacity
      ServiceNamespace: appstream
      SuspendedState:
        DynamicScalingInSuspended: false
        DynamicScalingOutSuspended: false
        ScheduledScalingSuspended: false
      ScheduledActions:
        - ScheduledActionName: !Sub "${FleetName}-scale-up-business-hours"
          Schedule: !Ref BusinessHoursCronStartUTC
          ScalableTargetAction:
            MinCapacity: 1
        - ScheduledActionName: !Sub "${FleetName}-scale-down-after-hours"
          Schedule: !Ref AfterHoursCronStopUTC
          ScalableTargetAction:
            MinCapacity: 0
            MaxCapacity: 0

  ScaleOutPolicy:
    Condition: EnableScaling
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub "${FleetName}-scaleout"
      PolicyType: StepScaling
      ScalingTargetId: !Ref ScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 120
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalLowerBound: 0
            ScalingAdjustment: 1

  ScaleInPolicy:
    Condition: EnableScaling
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub "${FleetName}-scalein"
      PolicyType: StepScaling
      ScalingTargetId: !Ref ScalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 300
        MetricAggregationType: Average
        StepAdjustments:
          - MetricIntervalUpperBound: 0
            ScalingAdjustment: -1

  HighUtilizationAlarm:
    Condition: EnableScaling
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Scale out when capacity utilization >= 75%"
      Namespace: "AWS/AppStream"
      MetricName: "CapacityUtilization"
      Dimensions:
        - Name: Fleet
          Value: !Ref FleetName
      Statistic: Average
      Period: 60
      EvaluationPeriods: 5
      Threshold: 75
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: "notBreaching"   # <-- quote; exact value
      AlarmActions:
        - !Ref ScaleOutPolicy

  LowUtilizationAlarm:
    Condition: EnableScaling
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Scale in when capacity utilization <= 25%"
      Namespace: "AWS/AppStream"
      MetricName: "CapacityUtilization"
      Dimensions:
        - Name: Fleet
          Value: !Ref FleetName
      Statistic: Average
      Period: 60
      EvaluationPeriods: 10
      Threshold: 25
      ComparisonOperator: LessThanOrEqualToThreshold
      TreatMissingData: "notBreaching"   # <-- quote; exact value
      AlarmActions:
        - !Ref ScaleInPolicy

Outputs:
  FleetName:
    Value: !Ref AppStreamFleet
    Description: AppStream Fleet name
  StackName:
    Value: !Ref AppStreamStack
    Description: AppStream Stack name
  ImageBuilderName:
    Condition: CreateImageBuilder
    Value: !Ref ImageBuilder
    Description: ImageBuilder name
