AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Webforx AppStream VDI Stack with Auto Scaling and 4-hour session timeout.

Parameters:
  VPCId:
    Type: String
  SubnetIds:
    Type: CommaDelimitedList
  SecurityGroupId:
    Type: String
  FleetName:
    Type: String
    Default: webforx-vdi-fleet
  MinCapacity:
    Type: Number
    Default: 0
  DesiredCapacity:
    Type: Number
    Default: 0
  MaxCapacity:
    Type: Number
    Default: 5
  MaxUserSessionDurationHours:
    Type: Number
    Default: 4
  EnableAutoScaling:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "true"

Mappings: {}

Resources:
  AppStreamFleet:
    Type: AWS::AppStream::Fleet
    Properties:
      Name: !Ref FleetName
      InstanceType: stream.standard.medium
      ComputeCapacity:
        DesiredInstances: !Ref DesiredCapacity
      VpcConfig:
        SecurityGroupIds: [!Ref SecurityGroupId]
        SubnetIds: !Ref SubnetIds
      StreamView: APPLICATION
      MaxUserDurationInSeconds: !FindInMap [SessionMap, Default, MaxSeconds] # replaced via Condition/Calc below
      DisconnectTimeoutInSeconds: 900
      IdleDisconnectTimeoutInSeconds: 900
      EnableDefaultInternetAccess: false
      FleetType: ON_DEMAND

  # Calculate seconds for MaxUserSessionDurationHours
  SessionParams:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/webforx/appstream/${FleetName}/max_session_seconds"
      Type: String
      Value: !Sub "${MaxUserSessionDurationHours} * 3600"
      Tags:
        Project: appstream-vdi

  ScalingPolicy:
    Type: AWS::AppStream::Fleet
    Condition: EnableAutoScalingCondition
    Properties:
      Name: !Ref FleetName
      InstanceType: stream.standard.medium
      ComputeCapacity:
        DesiredInstances: !Ref DesiredCapacity
      VpcConfig:
        SecurityGroupIds: [!Ref SecurityGroupId]
        SubnetIds: !Ref SubnetIds

Conditions:
  EnableAutoScalingCondition: !Equals [!Ref EnableAutoScaling, "true"]

Outputs:
  FleetName:
    Value: !Ref AppStreamFleet
    Description: The AppStream Fleet name

  StackStatus:
    Value: "CREATED"
