# .github/workflows/aws-oidc-smoke.yml
name: OIDC smoke test
on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  sts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: us-east-1
          role-session-name: gha-oidc-smoke

      - name: Who am I?
        run: aws sts get-caller-identity
