name: OIDC to AWS (Test)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]  # match the branch in the trust policy

permissions:
  id-token: write        # <-- required for OIDC
  contents: read

jobs:
  test-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::108188564905:role/GitHubActionsDeployRole
          aws-region: us-east-1   # change if needed
          role-session-name: gha-oidc-demo

      - name: Who am I?
        run: aws sts get-caller-identity

      # Example: dry-run put to S3 (safe test)
      - name: Dry-run upload
        run: |
          echo "hello from OIDC" > file.txt
          aws s3 cp file.txt s3://edusuc-bucket/file.txt

