name: Enforce Branch Naming Convention
on:
  push:
    branches:
      - "main"
jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Get Branch Name
        id: branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Validate Branch Name
        run: |
          if [[ ! "${{ env.branch_name }}" =~ ^(feature|bug|hotfix|chore|release)\/[a-zA-Z0-9._-]+$ && "${{ env.branch_name }}" != "develop" && "${{ env.branch_name }}" != "production" ]]; then
            echo ":rotating_light: ERROR: Invalid branch name '${{ env.branch_name }}'."
            exit 1
          fi
