name: Terraform CI/CD

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (sandbox, dev, stage, prod, webforx-management)"
        required: true
        default: "sandbox"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
          terraform_wrapper: false

      - name: Print GitHub context
        run: echo "${{ toJson(github) }}"

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: gha-appstream

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (PR)
        if: github.event_name == 'pull_request'
        run: terraform plan -var="environment=${{ github.event.inputs.environment }}" -out=tfplan

      - name: Terraform Plan (Manual Dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: terraform plan -var="environment=${{ github.event.inputs.environment }}" -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        env:
          # Require manual approval before execution (set via GitHub Environments for production)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
